// Code generated by librarian. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"os"

	accessapproval "github.com/julieqiu/gcloud/generated/accessapproval"
	accesscontextmanager "github.com/julieqiu/gcloud/generated/accesscontextmanager"
	advisorynotifications "github.com/julieqiu/gcloud/generated/advisorynotifications"
	aiplatform "github.com/julieqiu/gcloud/generated/aiplatform"
	alloydb "github.com/julieqiu/gcloud/generated/alloydb"
	alloydbconnectors "github.com/julieqiu/gcloud/generated/alloydbconnectors"
	apigateway "github.com/julieqiu/gcloud/generated/apigateway"
	apigeeconnect "github.com/julieqiu/gcloud/generated/apigeeconnect"
	apihub "github.com/julieqiu/gcloud/generated/apihub"
	apiregistry "github.com/julieqiu/gcloud/generated/apiregistry"
	appengine "github.com/julieqiu/gcloud/generated/appengine"
	apphub "github.com/julieqiu/gcloud/generated/apphub"
	artifactregistry "github.com/julieqiu/gcloud/generated/artifactregistry"
	asset "github.com/julieqiu/gcloud/generated/asset"
	assuredworkloads "github.com/julieqiu/gcloud/generated/assuredworkloads"
	auditmanager "github.com/julieqiu/gcloud/generated/auditmanager"
	backupdr "github.com/julieqiu/gcloud/generated/backupdr"
	baremetalsolution "github.com/julieqiu/gcloud/generated/baremetalsolution"
	beyondcorpappconnections "github.com/julieqiu/gcloud/generated/beyondcorpappconnections"
	beyondcorpappconnectors "github.com/julieqiu/gcloud/generated/beyondcorpappconnectors"
	beyondcorpappgateways "github.com/julieqiu/gcloud/generated/beyondcorpappgateways"
	beyondcorpclientconnectorservices "github.com/julieqiu/gcloud/generated/beyondcorpclientconnectorservices"
	beyondcorpclientgateways "github.com/julieqiu/gcloud/generated/beyondcorpclientgateways"
	biglake "github.com/julieqiu/gcloud/generated/biglake"
	bigquery "github.com/julieqiu/gcloud/generated/bigquery"
	bigqueryanalyticshub "github.com/julieqiu/gcloud/generated/bigqueryanalyticshub"
	bigqueryconnection "github.com/julieqiu/gcloud/generated/bigqueryconnection"
	bigquerydatapolicies "github.com/julieqiu/gcloud/generated/bigquerydatapolicies"
	bigquerydatatransfer "github.com/julieqiu/gcloud/generated/bigquerydatatransfer"
	bigquerymigration "github.com/julieqiu/gcloud/generated/bigquerymigration"
	bigqueryreservation "github.com/julieqiu/gcloud/generated/bigqueryreservation"
	bigtableadmin "github.com/julieqiu/gcloud/generated/bigtableadmin"
	billing "github.com/julieqiu/gcloud/generated/billing"
	binaryauthorization "github.com/julieqiu/gcloud/generated/binaryauthorization"
	blockchainnodeengine "github.com/julieqiu/gcloud/generated/blockchainnodeengine"
	certificatemanager "github.com/julieqiu/gcloud/generated/certificatemanager"
	ces "github.com/julieqiu/gcloud/generated/ces"
	chronicle "github.com/julieqiu/gcloud/generated/chronicle"
	cloudbuild "github.com/julieqiu/gcloud/generated/cloudbuild"
	cloudcontrolspartner "github.com/julieqiu/gcloud/generated/cloudcontrolspartner"
	clouddms "github.com/julieqiu/gcloud/generated/clouddms"
	cloudquotas "github.com/julieqiu/gcloud/generated/cloudquotas"
	cloudsecuritycompliance "github.com/julieqiu/gcloud/generated/cloudsecuritycompliance"
	cloudtrace "github.com/julieqiu/gcloud/generated/cloudtrace"
	commerceconsumerprocurement "github.com/julieqiu/gcloud/generated/commerceconsumerprocurement"
	compute "github.com/julieqiu/gcloud/generated/compute"
	confidentialcomputing "github.com/julieqiu/gcloud/generated/confidentialcomputing"
	config "github.com/julieqiu/gcloud/generated/config"
	configdelivery "github.com/julieqiu/gcloud/generated/configdelivery"
	connectors "github.com/julieqiu/gcloud/generated/connectors"
	contactcenterinsights "github.com/julieqiu/gcloud/generated/contactcenterinsights"
	datacatalog "github.com/julieqiu/gcloud/generated/datacatalog"
	datacataloglineage "github.com/julieqiu/gcloud/generated/datacataloglineage"
	datacataloglineageconfigmanagement "github.com/julieqiu/gcloud/generated/datacataloglineageconfigmanagement"
	dataform "github.com/julieqiu/gcloud/generated/dataform"
	datafusion "github.com/julieqiu/gcloud/generated/datafusion"
	dataplex "github.com/julieqiu/gcloud/generated/dataplex"
	dataproc "github.com/julieqiu/gcloud/generated/dataproc"
	datastream "github.com/julieqiu/gcloud/generated/datastream"
	deploy "github.com/julieqiu/gcloud/generated/deploy"
	developerconnect "github.com/julieqiu/gcloud/generated/developerconnect"
	devicestreaming "github.com/julieqiu/gcloud/generated/devicestreaming"
	dialogflow "github.com/julieqiu/gcloud/generated/dialogflow"
	dialogflowcx "github.com/julieqiu/gcloud/generated/dialogflowcx"
	discoveryengine "github.com/julieqiu/gcloud/generated/discoveryengine"
	dlp "github.com/julieqiu/gcloud/generated/dlp"
	documentai "github.com/julieqiu/gcloud/generated/documentai"
	domains "github.com/julieqiu/gcloud/generated/domains"
	edgecontainer "github.com/julieqiu/gcloud/generated/edgecontainer"
	edgenetwork "github.com/julieqiu/gcloud/generated/edgenetwork"
	essentialcontacts "github.com/julieqiu/gcloud/generated/essentialcontacts"
	eventarc "github.com/julieqiu/gcloud/generated/eventarc"
	eventarcpublishing "github.com/julieqiu/gcloud/generated/eventarcpublishing"
	filestore "github.com/julieqiu/gcloud/generated/filestore"
	financialservices "github.com/julieqiu/gcloud/generated/financialservices"
	firestore "github.com/julieqiu/gcloud/generated/firestore"
	functions "github.com/julieqiu/gcloud/generated/functions"
	gkebackup "github.com/julieqiu/gcloud/generated/gkebackup"
	gkeconnectgateway "github.com/julieqiu/gcloud/generated/gkeconnectgateway"
	gkehub "github.com/julieqiu/gcloud/generated/gkehub"
	gkemulticloud "github.com/julieqiu/gcloud/generated/gkemulticloud"
	gkerecommender "github.com/julieqiu/gcloud/generated/gkerecommender"
	gsuiteaddons "github.com/julieqiu/gcloud/generated/gsuiteaddons"
	hypercomputecluster "github.com/julieqiu/gcloud/generated/hypercomputecluster"
	iam "github.com/julieqiu/gcloud/generated/iam"
	iamcredentials "github.com/julieqiu/gcloud/generated/iamcredentials"
	iap "github.com/julieqiu/gcloud/generated/iap"
	identitytoolkit "github.com/julieqiu/gcloud/generated/identitytoolkit"
	ids "github.com/julieqiu/gcloud/generated/ids"
	iot "github.com/julieqiu/gcloud/generated/iot"
	kms "github.com/julieqiu/gcloud/generated/kms"
	kmsinventory "github.com/julieqiu/gcloud/generated/kmsinventory"
	language "github.com/julieqiu/gcloud/generated/language"
	licensemanager "github.com/julieqiu/gcloud/generated/licensemanager"
	locationfinder "github.com/julieqiu/gcloud/generated/locationfinder"
	logging "github.com/julieqiu/gcloud/generated/logging"
	lustre "github.com/julieqiu/gcloud/generated/lustre"
	maintenanceapi "github.com/julieqiu/gcloud/generated/maintenanceapi"
	managedidentities "github.com/julieqiu/gcloud/generated/managedidentities"
	managedkafka "github.com/julieqiu/gcloud/generated/managedkafka"
	managedkafkaschemaregistry "github.com/julieqiu/gcloud/generated/managedkafkaschemaregistry"
	memcache "github.com/julieqiu/gcloud/generated/memcache"
	memorystore "github.com/julieqiu/gcloud/generated/memorystore"
	metastore "github.com/julieqiu/gcloud/generated/metastore"
	migrationcenter "github.com/julieqiu/gcloud/generated/migrationcenter"
	modelarmor "github.com/julieqiu/gcloud/generated/modelarmor"
	monitoring "github.com/julieqiu/gcloud/generated/monitoring"
	netapp "github.com/julieqiu/gcloud/generated/netapp"
	networkconnectivity "github.com/julieqiu/gcloud/generated/networkconnectivity"
	networkmanagement "github.com/julieqiu/gcloud/generated/networkmanagement"
	networksecurity "github.com/julieqiu/gcloud/generated/networksecurity"
	networkservices "github.com/julieqiu/gcloud/generated/networkservices"
	notebooks "github.com/julieqiu/gcloud/generated/notebooks"
	optimization "github.com/julieqiu/gcloud/generated/optimization"
	oracledatabase "github.com/julieqiu/gcloud/generated/oracledatabase"
	orchestrationairflowservice "github.com/julieqiu/gcloud/generated/orchestrationairflowservice"
	orgpolicy "github.com/julieqiu/gcloud/generated/orgpolicy"
	osconfig "github.com/julieqiu/gcloud/generated/osconfig"
	osconfigagentendpoint "github.com/julieqiu/gcloud/generated/osconfigagentendpoint"
	oslogin "github.com/julieqiu/gcloud/generated/oslogin"
	parallelstore "github.com/julieqiu/gcloud/generated/parallelstore"
	parametermanager "github.com/julieqiu/gcloud/generated/parametermanager"
	paymentgatewayissuerswitch "github.com/julieqiu/gcloud/generated/paymentgatewayissuerswitch"
	paymentgatewayissuerswitchaccountmanager "github.com/julieqiu/gcloud/generated/paymentgatewayissuerswitchaccountmanager"
	policysimulator "github.com/julieqiu/gcloud/generated/policysimulator"
	policytroubleshooter "github.com/julieqiu/gcloud/generated/policytroubleshooter"
	policytroubleshooteriam "github.com/julieqiu/gcloud/generated/policytroubleshooteriam"
	privateca "github.com/julieqiu/gcloud/generated/privateca"
	privilegedaccessmanager "github.com/julieqiu/gcloud/generated/privilegedaccessmanager"
	publicca "github.com/julieqiu/gcloud/generated/publicca"
	pubsub "github.com/julieqiu/gcloud/generated/pubsub"
	pubsublite "github.com/julieqiu/gcloud/generated/pubsublite"
	rapidmigrationassessment "github.com/julieqiu/gcloud/generated/rapidmigrationassessment"
	recaptchaenterprise "github.com/julieqiu/gcloud/generated/recaptchaenterprise"
	recommender "github.com/julieqiu/gcloud/generated/recommender"
	redis "github.com/julieqiu/gcloud/generated/redis"
	rediscluster "github.com/julieqiu/gcloud/generated/rediscluster"
	resourcemanager "github.com/julieqiu/gcloud/generated/resourcemanager"
	retail "github.com/julieqiu/gcloud/generated/retail"
	run "github.com/julieqiu/gcloud/generated/run"
	scheduler "github.com/julieqiu/gcloud/generated/scheduler"
	secretmanager "github.com/julieqiu/gcloud/generated/secretmanager"
	securesourcemanager "github.com/julieqiu/gcloud/generated/securesourcemanager"
	securitycenter "github.com/julieqiu/gcloud/generated/securitycenter"
	securitycentermanagement "github.com/julieqiu/gcloud/generated/securitycentermanagement"
	securityposture "github.com/julieqiu/gcloud/generated/securityposture"
	servicedirectory "github.com/julieqiu/gcloud/generated/servicedirectory"
	servicehealth "github.com/julieqiu/gcloud/generated/servicehealth"
	servicemanagement "github.com/julieqiu/gcloud/generated/servicemanagement"
	serviceusage "github.com/julieqiu/gcloud/generated/serviceusage"
	shell "github.com/julieqiu/gcloud/generated/shell"
	spanner "github.com/julieqiu/gcloud/generated/spanner"
	speech "github.com/julieqiu/gcloud/generated/speech"
	sql "github.com/julieqiu/gcloud/generated/sql"
	storagebatchoperations "github.com/julieqiu/gcloud/generated/storagebatchoperations"
	storageinsights "github.com/julieqiu/gcloud/generated/storageinsights"
	storagetransfer "github.com/julieqiu/gcloud/generated/storagetransfer"
	support "github.com/julieqiu/gcloud/generated/support"
	talent "github.com/julieqiu/gcloud/generated/talent"
	tasks "github.com/julieqiu/gcloud/generated/tasks"
	telcoautomation "github.com/julieqiu/gcloud/generated/telcoautomation"
	texttospeech "github.com/julieqiu/gcloud/generated/texttospeech"
	timeseriesinsights "github.com/julieqiu/gcloud/generated/timeseriesinsights"
	tpu "github.com/julieqiu/gcloud/generated/tpu"
	translate "github.com/julieqiu/gcloud/generated/translate"
	universalledger "github.com/julieqiu/gcloud/generated/universalledger"
	vectorsearch "github.com/julieqiu/gcloud/generated/vectorsearch"
	videointelligence "github.com/julieqiu/gcloud/generated/videointelligence"
	videolivestream "github.com/julieqiu/gcloud/generated/videolivestream"
	videostitcher "github.com/julieqiu/gcloud/generated/videostitcher"
	videotranscoder "github.com/julieqiu/gcloud/generated/videotranscoder"
	vision "github.com/julieqiu/gcloud/generated/vision"
	visionai "github.com/julieqiu/gcloud/generated/visionai"
	vmmigration "github.com/julieqiu/gcloud/generated/vmmigration"
	vmwareengine "github.com/julieqiu/gcloud/generated/vmwareengine"
	vpcaccess "github.com/julieqiu/gcloud/generated/vpcaccess"
	webrisk "github.com/julieqiu/gcloud/generated/webrisk"
	websecurityscanner "github.com/julieqiu/gcloud/generated/websecurityscanner"
	workflows "github.com/julieqiu/gcloud/generated/workflows"
	workflowsexecutions "github.com/julieqiu/gcloud/generated/workflowsexecutions"
	workloadmanager "github.com/julieqiu/gcloud/generated/workloadmanager"
	workstations "github.com/julieqiu/gcloud/generated/workstations"
	"github.com/urfave/cli/v3"
)

func main() {
	app := &cli.Command{
		Name:  "gcloud",
		Usage: "Google Cloud CLI",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "project", Usage: "The project."},
		},
		Commands: []*cli.Command{
			accessapproval.Command(),
			accesscontextmanager.Command(),
			advisorynotifications.Command(),
			aiplatform.Command(),
			alloydb.Command(),
			alloydbconnectors.Command(),
			apigateway.Command(),
			apigeeconnect.Command(),
			apihub.Command(),
			apiregistry.Command(),
			appengine.Command(),
			apphub.Command(),
			artifactregistry.Command(),
			asset.Command(),
			assuredworkloads.Command(),
			auditmanager.Command(),
			backupdr.Command(),
			baremetalsolution.Command(),
			beyondcorpappconnections.Command(),
			beyondcorpappconnectors.Command(),
			beyondcorpappgateways.Command(),
			beyondcorpclientconnectorservices.Command(),
			beyondcorpclientgateways.Command(),
			biglake.Command(),
			bigquery.Command(),
			bigqueryanalyticshub.Command(),
			bigqueryconnection.Command(),
			bigquerydatapolicies.Command(),
			bigquerydatatransfer.Command(),
			bigquerymigration.Command(),
			bigqueryreservation.Command(),
			bigtableadmin.Command(),
			billing.Command(),
			binaryauthorization.Command(),
			blockchainnodeengine.Command(),
			certificatemanager.Command(),
			ces.Command(),
			chronicle.Command(),
			cloudbuild.Command(),
			cloudcontrolspartner.Command(),
			clouddms.Command(),
			cloudquotas.Command(),
			cloudsecuritycompliance.Command(),
			cloudtrace.Command(),
			commerceconsumerprocurement.Command(),
			compute.Command(),
			confidentialcomputing.Command(),
			config.Command(),
			configdelivery.Command(),
			connectors.Command(),
			contactcenterinsights.Command(),
			datacatalog.Command(),
			datacataloglineage.Command(),
			datacataloglineageconfigmanagement.Command(),
			dataform.Command(),
			datafusion.Command(),
			dataplex.Command(),
			dataproc.Command(),
			datastream.Command(),
			deploy.Command(),
			developerconnect.Command(),
			devicestreaming.Command(),
			dialogflow.Command(),
			dialogflowcx.Command(),
			discoveryengine.Command(),
			dlp.Command(),
			documentai.Command(),
			domains.Command(),
			edgecontainer.Command(),
			edgenetwork.Command(),
			essentialcontacts.Command(),
			eventarc.Command(),
			eventarcpublishing.Command(),
			filestore.Command(),
			financialservices.Command(),
			firestore.Command(),
			functions.Command(),
			gkebackup.Command(),
			gkeconnectgateway.Command(),
			gkehub.Command(),
			gkemulticloud.Command(),
			gkerecommender.Command(),
			gsuiteaddons.Command(),
			hypercomputecluster.Command(),
			iam.Command(),
			iamcredentials.Command(),
			iap.Command(),
			identitytoolkit.Command(),
			ids.Command(),
			iot.Command(),
			kms.Command(),
			kmsinventory.Command(),
			language.Command(),
			licensemanager.Command(),
			locationfinder.Command(),
			logging.Command(),
			lustre.Command(),
			maintenanceapi.Command(),
			managedidentities.Command(),
			managedkafka.Command(),
			managedkafkaschemaregistry.Command(),
			memcache.Command(),
			memorystore.Command(),
			metastore.Command(),
			migrationcenter.Command(),
			modelarmor.Command(),
			monitoring.Command(),
			netapp.Command(),
			networkconnectivity.Command(),
			networkmanagement.Command(),
			networksecurity.Command(),
			networkservices.Command(),
			notebooks.Command(),
			optimization.Command(),
			oracledatabase.Command(),
			orchestrationairflowservice.Command(),
			orgpolicy.Command(),
			osconfig.Command(),
			osconfigagentendpoint.Command(),
			oslogin.Command(),
			parallelstore.Command(),
			parametermanager.Command(),
			paymentgatewayissuerswitch.Command(),
			paymentgatewayissuerswitchaccountmanager.Command(),
			policysimulator.Command(),
			policytroubleshooter.Command(),
			policytroubleshooteriam.Command(),
			privateca.Command(),
			privilegedaccessmanager.Command(),
			publicca.Command(),
			pubsub.Command(),
			pubsublite.Command(),
			rapidmigrationassessment.Command(),
			recaptchaenterprise.Command(),
			recommender.Command(),
			redis.Command(),
			rediscluster.Command(),
			resourcemanager.Command(),
			retail.Command(),
			run.Command(),
			scheduler.Command(),
			secretmanager.Command(),
			securesourcemanager.Command(),
			securitycenter.Command(),
			securitycentermanagement.Command(),
			securityposture.Command(),
			servicedirectory.Command(),
			servicehealth.Command(),
			servicemanagement.Command(),
			serviceusage.Command(),
			shell.Command(),
			spanner.Command(),
			speech.Command(),
			sql.Command(),
			storagebatchoperations.Command(),
			storageinsights.Command(),
			storagetransfer.Command(),
			support.Command(),
			talent.Command(),
			tasks.Command(),
			telcoautomation.Command(),
			texttospeech.Command(),
			timeseriesinsights.Command(),
			tpu.Command(),
			translate.Command(),
			universalledger.Command(),
			vectorsearch.Command(),
			videointelligence.Command(),
			videolivestream.Command(),
			videostitcher.Command(),
			videotranscoder.Command(),
			vision.Command(),
			visionai.Command(),
			vmmigration.Command(),
			vmwareengine.Command(),
			vpcaccess.Command(),
			webrisk.Command(),
			websecurityscanner.Command(),
			workflows.Command(),
			workflowsexecutions.Command(),
			workloadmanager.Command(),
			workstations.Command(),
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}
